#!/bin/bash

controlStat=$(stat -c %Y "/etc/crontab")
while sleep 1; do liveStat=$(stat -c %Y "/etc/crontab")
    if [[ $liveStat != $controlStat ]]; then echo "MODIFIED" | mutt -s "file was modified" root@localhost < /dev/null; break; fi
done

echo "0 0 * * * ./Path/To/File/$0 &" | crontab